Added methods for /error/ID/done and /error/ID/false routes
GuillaumeAmat/osmose-request pull request #2
Opened 2018-01-11 14:42 UTC by PanierAvide

Should do the job for #1

2018-01-14 10:53 UTC, GuillaumeAmat requested changes

2018-01-14 10:53 UTC, GuillaumeAmat commented on src/__tests__/index.test.js
> +  let errors = await osmose.fetchErrors({ item: 8120 });
You should use `const` here

2018-01-14 10:53 UTC, GuillaumeAmat commented on src/__tests__/index.test.js
> +    const result = await osmose.closeError(errorId);
You forgot to create a mock in the `src/__mocks__/requests.js` file. So you are actually calling the Osmose service and close an error :/

2018-01-14 10:53 UTC, GuillaumeAmat commented on src/__tests__/index.test.js
> +    const result = await osmose.falseError(errorId);
Same thing here about the mock :/

2018-01-14 10:54 UTC, GuillaumeAmat commented
Thank you @PanierAvide! o/

Your work is very clean, it misses mocks by the way, be careful to your tests until you create them.

2018-01-14 11:53 UTC, PanierAvide commented
I will do the requested changes, I wasn't aware of the mocks (still learning modern JS !). I will update this soon, thanks for the review :-)

2018-01-14 12:27 UTC, PanierAvide commented
Done ;-)

2018-01-14 12:35 UTC, GuillaumeAmat commented
I think you misunderstood the purpose of mocks. They are here to replace real functions and so, acting like them.

In the current subject, the mocks have to prevent the call of real API routes. So your mock functions have to act like the real functions by returning proper results.

If you look at the previous mocks, they all return a JSON object that should be returned by the real API route. You have to do the same thing and not returning an html content telling us that the call raised an error.

2018-01-14 12:39 UTC, PanierAvide commented
The problem is that for these routes, the Osmose API returns really this kind of response, and not a clean JSON. The fact that page says it's an error when showing `OK 200` is weird, particularly when you see that API has taken into account the change.

2018-01-14 12:44 UTC, GuillaumeAmat commented
Oh crap... I think we should report it to the Osmose project, don't you think? That kind of behavior is not ideal in my opinion...

Anyway, you're PR is great, I merge it right now thank you!

2018-01-14 12:44 UTC, GuillaumeAmat approved these changes

2018-01-14 12:45 UTC, GuillaumeAmat commented
Woops, I did not saw that the coverage decreased... I think there is a missing point.

2018-01-14 12:46 UTC, PanierAvide commented
Well the API issue is probably related to https://github.com/osm-fr/osmose-backend/issues/259

2018-01-14 12:56 UTC, GuillaumeAmat requested changes

2018-01-14 12:56 UTC, GuillaumeAmat commented on src/__tests__/index.test.js
> +    defaultOptions.endpoint,
There is a quirk here ^^

2018-01-14 13:06 UTC, GuillaumeAmat requested changes

2018-01-14 13:06 UTC, GuillaumeAmat commented on src/__tests__/index.test.js
> +describe('Update Osmose errors', async () => {
Ok got it! `describe` are not meant to be `async`.

2018-01-14 13:06 UTC, GuillaumeAmat commented on src/__tests__/index.test.js
> +  const errors = await osmose.fetchErrors({ item: 8120 });
... So you have to fetch the errors in each `it` (not a perf problem since we have mocks)

2018-01-14 13:07 UTC, GuillaumeAmat commented
Furthermore, can you add your methods to the README?

2018-01-14 13:09 UTC, GuillaumeAmat requested changes

2018-01-14 13:09 UTC, GuillaumeAmat commented on src/__tests__/index.test.js
> +    defaultOptions.endpoint,
You still have the `defaultOptions.endpoint,` weirdness ;)

2018-01-14 13:35 UTC, GuillaumeAmat approved these changes

2018-01-14 13:35 UTC, GuillaumeAmat commented
The journey is over! ;)
Thanks again @PanierAvide

2018-01-14 13:35 UTC, merged

2018-01-14 13:36 UTC, PanierAvide commented
Thanks for the review and integration :-)

2018-01-14 13:43 UTC, GuillaumeAmat commented
Published in the 1.1.1 released :)

2018-01-20 20:26 UTC, frodrigo commented
Osmose CORS issue should be fixed.

2018-01-20 20:51 UTC, PanierAvide commented
@frodrigo Thank you :-)

2018-01-20 21:28 UTC, GuillaumeAmat commented
Thanks @frodrigo